# Use the official Python image as the base image
FROM python:3.12-slim

# Install system dependencies for psycopg2
RUN apt-get update -y; \
    apt-get upgrade -y; \
    apt-get install -y\
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 && \
    apt-get clean
    # apt-get install -y libpq-dev && \

# Set the working directory in the container
WORKDIR /app

ENV PYTHONPATH=/app:$PYTHONPATH

# Copy the requirements file into the container
COPY requirements.txt requirements.txt

# Install required packages
RUN pip install -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the port that the FastAPI application will run on
EXPOSE 8000

# Command to run the FastAPI application
CMD ["fastapi","dev","--host", "0.0.0.0","--port","8000","src/interfaces/http/server.py"]